name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Git Pull and Build on Droplet
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} <<'ENDSSH'
          # Assuming you have a git repository cloned at /var/www/myapp
          cd /root/frontend
          
          # Pull the latest changes
          git pull
          
          # Build your project (e.g., a Vue or React application)
          yarn install
          yarn build
          
          # Optionally, move build artifacts to the desired location
          # This step depends on your specific setup. For example, for a Vue app:
          rm -rf /var/www/html/quizzebassen/*
          cp -R dist/* /var/www/html/quizzebassen/
        ENDSSH
