name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Git Pull and Build on Droplet
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} <<'ENDSSH'
          # Install NVM (Node Version Manager) if not already installed
          if ! command -v nvm &> /dev/null; then
              echo "NVM not found, installing..."
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
              # This loads nvm
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          fi

          # Load NVM scripts for this session
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

          # Install and use Node.js version 20
          nvm install 20
          nvm use 20

          # Verify Node and NPM versions
          node -v
          npm -v

          # Assuming you have a git repository cloned at /var/www/myapp
          cd /root/frontend
          
          # Check if Yarn is installed, install if not
          if ! command -v yarn &> /dev/null; then
              echo "Yarn not found, installing..."
              curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
              echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
              sudo apt-get update && sudo apt-get install yarn
          fi
          
          # Pull the latest changes
          git pull
          
          # Build your project (e.g., a Vue or React application)
          yarn install
          yarn build
          
          # Move build artifacts to the desired location
          rm -rf /var/www/html/quizzebassen/*
          cp -R dist/* /var/www/html/quizzebassen/
        ENDSSH


